/* <![CDATA[ */
var wpforms_settings = {
  val_required: "This field is required.",
  val_email: "Please enter a valid email address.",
  val_email_suggestion: "Did you mean {suggestion}?",
  val_email_suggestion_title: "Click to accept this suggestion.",
  val_email_restricted: "This email address is not allowed.",
  val_number: "Please enter a valid number.",
  val_number_positive: "Please enter a valid positive number.",
  val_minimum_price: "Amount entered is less than the required minimum.",
  val_confirm: "Field values do not match.",
  val_checklimit: "You have exceeded the number of allowed selections: {#}.",
  val_limit_characters: "{count} of {limit} max characters.",
  val_limit_words: "{count} of {limit} max words.",
  val_min: "Please enter a value greater than or equal to {0}.",
  val_max: "Please enter a value less than or equal to {0}.",
  val_recaptcha_fail_msg:
    "Google reCAPTCHA verification failed, please try again later.",
  val_turnstile_fail_msg:
    "Cloudflare Turnstile verification failed, please try again later.",
  val_inputmask_incomplete: "Please fill out the field in required format.",
  uuid_cookie: "",
  locale: "en",
  country: "",
  country_list_label: "Country list",
  wpforms_plugin_url:
    "https://websitedemos.net/communities-02/wp-content/plugins/wpforms-lite/",
  gdpr: "",
  ajaxurl: "https://websitedemos.net/communities-02/wp-admin/admin-ajax.php",
  mailcheck_enabled: "1",
  mailcheck_domains: [],
  mailcheck_toplevel_domains: ["dev"],
  is_ssl: "1",
  currency_code: "USD",
  currency_thousands: ",",
  currency_decimals: "2",
  currency_decimal: ".",
  currency_symbol: "$",
  currency_symbol_pos: "left",
  val_requiredpayment: "Payment is required.",
  val_creditcard: "Please enter a valid credit card number.",
  error_updating_token:
    "Error updating token. Please try again or contact support if the issue persists.",
  network_error:
    "Network error or server is unreachable. Check your connection or try again later.",
  token_cache_lifetime: "86400",
  hn_data: [],
  address_field: { list_countries_without_states: ["GB", "DE", "CH", "NL"] },
};
/* ]]> */
